/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAutomationsRouteImport } from './routes/_authenticated/admin/automations'
import { Route as AuthenticatedAdminDraftsRouteImport } from './routes/_authenticated/admin/drafts'
import { Route as AuthenticatedAdminKbRouteImport } from './routes/_authenticated/admin/kb'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminReviewRouteImport } from './routes/_authenticated/admin/review'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAutomationsIndexRouteImport } from './routes/_authenticated/automations/index'
import { Route as AuthenticatedAutomationsLogsRouteImport } from './routes/_authenticated/automations/logs'
import { Route as AuthenticatedAutomationsTelegramRouteImport } from './routes/_authenticated/automations/telegram'
import { Route as AuthenticatedChatbotIndexRouteImport } from './routes/_authenticated/chatbot/index'
import { Route as AuthenticatedChatbotKbRouteImport } from './routes/_authenticated/chatbot/kb'
import { Route as AuthenticatedChatbotLeadsRouteImport } from './routes/_authenticated/chatbot/leads'
import { Route as AuthenticatedChatbotLiveRouteImport } from './routes/_authenticated/chatbot/live'
import { Route as AuthenticatedChatbotReviewRouteImport } from './routes/_authenticated/chatbot/review'
import { Route as AuthenticatedEmailDraftsIndexRouteImport } from './routes/_authenticated/email-drafts/index'
import { Route as AuthenticatedEmailDraftsHistoryRouteImport } from './routes/_authenticated/email-drafts/history'
import { Route as AuthenticatedEmailDraftsKbSyncRouteImport } from './routes/_authenticated/email-drafts/kb-sync'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'
import { Route as ApiPublicWorkspaceRouteImport } from './routes/api/public/workspace'
import { Route as ApiWebhooksGmailNotificationsRouteImport } from './routes/api/webhooks/gmail-notifications'
import { Route as ApiWebhooksTelegramRouteImport } from './routes/api/webhooks/telegram'
import { Route as ApiPublicWebhooksGmailNotificationsRouteImport } from './routes/api/public/webhooks/gmail-notifications'
import { Route as ApiPublicWebhooksTelegramRouteImport } from './routes/api/public/webhooks/telegram'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAutomationsRoute =
  AuthenticatedAdminAutomationsRouteImport.update({
    id: '/admin/automations',
    path: '/admin/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDraftsRoute =
  AuthenticatedAdminDraftsRouteImport.update({
    id: '/admin/drafts',
    path: '/admin/drafts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminKbRoute = AuthenticatedAdminKbRouteImport.update({
  id: '/admin/kb',
  path: '/admin/kb',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminReviewRoute =
  AuthenticatedAdminReviewRouteImport.update({
    id: '/admin/review',
    path: '/admin/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationsIndexRoute =
  AuthenticatedAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationsLogsRoute =
  AuthenticatedAutomationsLogsRouteImport.update({
    id: '/automations/logs',
    path: '/automations/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationsTelegramRoute =
  AuthenticatedAutomationsTelegramRouteImport.update({
    id: '/automations/telegram',
    path: '/automations/telegram',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatbotIndexRoute =
  AuthenticatedChatbotIndexRouteImport.update({
    id: '/chatbot/',
    path: '/chatbot/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatbotKbRoute = AuthenticatedChatbotKbRouteImport.update({
  id: '/chatbot/kb',
  path: '/chatbot/kb',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatbotLeadsRoute =
  AuthenticatedChatbotLeadsRouteImport.update({
    id: '/chatbot/leads',
    path: '/chatbot/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatbotLiveRoute =
  AuthenticatedChatbotLiveRouteImport.update({
    id: '/chatbot/live',
    path: '/chatbot/live',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatbotReviewRoute =
  AuthenticatedChatbotReviewRouteImport.update({
    id: '/chatbot/review',
    path: '/chatbot/review',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmailDraftsIndexRoute =
  AuthenticatedEmailDraftsIndexRouteImport.update({
    id: '/email-drafts/',
    path: '/email-drafts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmailDraftsHistoryRoute =
  AuthenticatedEmailDraftsHistoryRouteImport.update({
    id: '/email-drafts/history',
    path: '/email-drafts/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmailDraftsKbSyncRoute =
  AuthenticatedEmailDraftsKbSyncRouteImport.update({
    id: '/email-drafts/kb-sync',
    path: '/email-drafts/kb-sync',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWorkspaceRoute = ApiPublicWorkspaceRouteImport.update({
  id: '/api/public/workspace',
  path: '/api/public/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksGmailNotificationsRoute =
  ApiWebhooksGmailNotificationsRouteImport.update({
    id: '/api/webhooks/gmail-notifications',
    path: '/api/webhooks/gmail-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksTelegramRoute = ApiWebhooksTelegramRouteImport.update({
  id: '/api/webhooks/telegram',
  path: '/api/webhooks/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksGmailNotificationsRoute =
  ApiPublicWebhooksGmailNotificationsRouteImport.update({
    id: '/api/public/webhooks/gmail-notifications',
    path: '/api/public/webhooks/gmail-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksTelegramRoute =
  ApiPublicWebhooksTelegramRouteImport.update({
    id: '/api/public/webhooks/telegram',
    path: '/api/public/webhooks/telegram',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/drafts': typeof AuthenticatedAdminDraftsRoute
  '/admin/kb': typeof AuthenticatedAdminKbRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/review': typeof AuthenticatedAdminReviewRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/automations/logs': typeof AuthenticatedAutomationsLogsRoute
  '/automations/telegram': typeof AuthenticatedAutomationsTelegramRoute
  '/chatbot/kb': typeof AuthenticatedChatbotKbRoute
  '/chatbot/leads': typeof AuthenticatedChatbotLeadsRoute
  '/chatbot/live': typeof AuthenticatedChatbotLiveRoute
  '/chatbot/review': typeof AuthenticatedChatbotReviewRoute
  '/email-drafts/history': typeof AuthenticatedEmailDraftsHistoryRoute
  '/email-drafts/kb-sync': typeof AuthenticatedEmailDraftsKbSyncRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/workspace': typeof ApiPublicWorkspaceRoute
  '/api/webhooks/gmail-notifications': typeof ApiWebhooksGmailNotificationsRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/chatbot/': typeof AuthenticatedChatbotIndexRoute
  '/email-drafts/': typeof AuthenticatedEmailDraftsIndexRoute
  '/api/public/webhooks/gmail-notifications': typeof ApiPublicWebhooksGmailNotificationsRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/admin/drafts': typeof AuthenticatedAdminDraftsRoute
  '/admin/kb': typeof AuthenticatedAdminKbRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/review': typeof AuthenticatedAdminReviewRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/automations/logs': typeof AuthenticatedAutomationsLogsRoute
  '/automations/telegram': typeof AuthenticatedAutomationsTelegramRoute
  '/chatbot/kb': typeof AuthenticatedChatbotKbRoute
  '/chatbot/leads': typeof AuthenticatedChatbotLeadsRoute
  '/chatbot/live': typeof AuthenticatedChatbotLiveRoute
  '/chatbot/review': typeof AuthenticatedChatbotReviewRoute
  '/email-drafts/history': typeof AuthenticatedEmailDraftsHistoryRoute
  '/email-drafts/kb-sync': typeof AuthenticatedEmailDraftsKbSyncRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/workspace': typeof ApiPublicWorkspaceRoute
  '/api/webhooks/gmail-notifications': typeof ApiWebhooksGmailNotificationsRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/automations': typeof AuthenticatedAutomationsIndexRoute
  '/chatbot': typeof AuthenticatedChatbotIndexRoute
  '/email-drafts': typeof AuthenticatedEmailDraftsIndexRoute
  '/api/public/webhooks/gmail-notifications': typeof ApiPublicWebhooksGmailNotificationsRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/automations': typeof AuthenticatedAdminAutomationsRoute
  '/_authenticated/admin/drafts': typeof AuthenticatedAdminDraftsRoute
  '/_authenticated/admin/kb': typeof AuthenticatedAdminKbRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/review': typeof AuthenticatedAdminReviewRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/automations/logs': typeof AuthenticatedAutomationsLogsRoute
  '/_authenticated/automations/telegram': typeof AuthenticatedAutomationsTelegramRoute
  '/_authenticated/chatbot/kb': typeof AuthenticatedChatbotKbRoute
  '/_authenticated/chatbot/leads': typeof AuthenticatedChatbotLeadsRoute
  '/_authenticated/chatbot/live': typeof AuthenticatedChatbotLiveRoute
  '/_authenticated/chatbot/review': typeof AuthenticatedChatbotReviewRoute
  '/_authenticated/email-drafts/history': typeof AuthenticatedEmailDraftsHistoryRoute
  '/_authenticated/email-drafts/kb-sync': typeof AuthenticatedEmailDraftsKbSyncRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
  '/api/public/workspace': typeof ApiPublicWorkspaceRoute
  '/api/webhooks/gmail-notifications': typeof ApiWebhooksGmailNotificationsRoute
  '/api/webhooks/telegram': typeof ApiWebhooksTelegramRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/automations/': typeof AuthenticatedAutomationsIndexRoute
  '/_authenticated/chatbot/': typeof AuthenticatedChatbotIndexRoute
  '/_authenticated/email-drafts/': typeof AuthenticatedEmailDraftsIndexRoute
  '/api/public/webhooks/gmail-notifications': typeof ApiPublicWebhooksGmailNotificationsRoute
  '/api/public/webhooks/telegram': typeof ApiPublicWebhooksTelegramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/settings'
    | '/admin/automations'
    | '/admin/drafts'
    | '/admin/kb'
    | '/admin/leads'
    | '/admin/review'
    | '/admin/settings'
    | '/automations/logs'
    | '/automations/telegram'
    | '/chatbot/kb'
    | '/chatbot/leads'
    | '/chatbot/live'
    | '/chatbot/review'
    | '/email-drafts/history'
    | '/email-drafts/kb-sync'
    | '/api/public/chat'
    | '/api/public/whatsapp'
    | '/api/public/workspace'
    | '/api/webhooks/gmail-notifications'
    | '/api/webhooks/telegram'
    | '/admin/'
    | '/automations/'
    | '/chatbot/'
    | '/email-drafts/'
    | '/api/public/webhooks/gmail-notifications'
    | '/api/public/webhooks/telegram'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard'
    | '/settings'
    | '/admin/automations'
    | '/admin/drafts'
    | '/admin/kb'
    | '/admin/leads'
    | '/admin/review'
    | '/admin/settings'
    | '/automations/logs'
    | '/automations/telegram'
    | '/chatbot/kb'
    | '/chatbot/leads'
    | '/chatbot/live'
    | '/chatbot/review'
    | '/email-drafts/history'
    | '/email-drafts/kb-sync'
    | '/api/public/chat'
    | '/api/public/whatsapp'
    | '/api/public/workspace'
    | '/api/webhooks/gmail-notifications'
    | '/api/webhooks/telegram'
    | '/admin'
    | '/automations'
    | '/chatbot'
    | '/email-drafts'
    | '/api/public/webhooks/gmail-notifications'
    | '/api/public/webhooks/telegram'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/admin/automations'
    | '/_authenticated/admin/drafts'
    | '/_authenticated/admin/kb'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/review'
    | '/_authenticated/admin/settings'
    | '/_authenticated/automations/logs'
    | '/_authenticated/automations/telegram'
    | '/_authenticated/chatbot/kb'
    | '/_authenticated/chatbot/leads'
    | '/_authenticated/chatbot/live'
    | '/_authenticated/chatbot/review'
    | '/_authenticated/email-drafts/history'
    | '/_authenticated/email-drafts/kb-sync'
    | '/api/public/chat'
    | '/api/public/whatsapp'
    | '/api/public/workspace'
    | '/api/webhooks/gmail-notifications'
    | '/api/webhooks/telegram'
    | '/_authenticated/admin/'
    | '/_authenticated/automations/'
    | '/_authenticated/chatbot/'
    | '/_authenticated/email-drafts/'
    | '/api/public/webhooks/gmail-notifications'
    | '/api/public/webhooks/telegram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
  ApiPublicWorkspaceRoute: typeof ApiPublicWorkspaceRoute
  ApiWebhooksGmailNotificationsRoute: typeof ApiWebhooksGmailNotificationsRoute
  ApiWebhooksTelegramRoute: typeof ApiWebhooksTelegramRoute
  ApiPublicWebhooksGmailNotificationsRoute: typeof ApiPublicWebhooksGmailNotificationsRoute
  ApiPublicWebhooksTelegramRoute: typeof ApiPublicWebhooksTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/automations': {
      id: '/_authenticated/admin/automations'
      path: '/admin/automations'
      fullPath: '/admin/automations'
      preLoaderRoute: typeof AuthenticatedAdminAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/drafts': {
      id: '/_authenticated/admin/drafts'
      path: '/admin/drafts'
      fullPath: '/admin/drafts'
      preLoaderRoute: typeof AuthenticatedAdminDraftsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/kb': {
      id: '/_authenticated/admin/kb'
      path: '/admin/kb'
      fullPath: '/admin/kb'
      preLoaderRoute: typeof AuthenticatedAdminKbRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/review': {
      id: '/_authenticated/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AuthenticatedAdminReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations/': {
      id: '/_authenticated/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AuthenticatedAutomationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations/logs': {
      id: '/_authenticated/automations/logs'
      path: '/automations/logs'
      fullPath: '/automations/logs'
      preLoaderRoute: typeof AuthenticatedAutomationsLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations/telegram': {
      id: '/_authenticated/automations/telegram'
      path: '/automations/telegram'
      fullPath: '/automations/telegram'
      preLoaderRoute: typeof AuthenticatedAutomationsTelegramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot/': {
      id: '/_authenticated/chatbot/'
      path: '/chatbot'
      fullPath: '/chatbot/'
      preLoaderRoute: typeof AuthenticatedChatbotIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot/kb': {
      id: '/_authenticated/chatbot/kb'
      path: '/chatbot/kb'
      fullPath: '/chatbot/kb'
      preLoaderRoute: typeof AuthenticatedChatbotKbRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot/leads': {
      id: '/_authenticated/chatbot/leads'
      path: '/chatbot/leads'
      fullPath: '/chatbot/leads'
      preLoaderRoute: typeof AuthenticatedChatbotLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot/live': {
      id: '/_authenticated/chatbot/live'
      path: '/chatbot/live'
      fullPath: '/chatbot/live'
      preLoaderRoute: typeof AuthenticatedChatbotLiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chatbot/review': {
      id: '/_authenticated/chatbot/review'
      path: '/chatbot/review'
      fullPath: '/chatbot/review'
      preLoaderRoute: typeof AuthenticatedChatbotReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-drafts/': {
      id: '/_authenticated/email-drafts/'
      path: '/email-drafts'
      fullPath: '/email-drafts/'
      preLoaderRoute: typeof AuthenticatedEmailDraftsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-drafts/history': {
      id: '/_authenticated/email-drafts/history'
      path: '/email-drafts/history'
      fullPath: '/email-drafts/history'
      preLoaderRoute: typeof AuthenticatedEmailDraftsHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-drafts/kb-sync': {
      id: '/_authenticated/email-drafts/kb-sync'
      path: '/email-drafts/kb-sync'
      fullPath: '/email-drafts/kb-sync'
      preLoaderRoute: typeof AuthenticatedEmailDraftsKbSyncRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/workspace': {
      id: '/api/public/workspace'
      path: '/api/public/workspace'
      fullPath: '/api/public/workspace'
      preLoaderRoute: typeof ApiPublicWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/gmail-notifications': {
      id: '/api/webhooks/gmail-notifications'
      path: '/api/webhooks/gmail-notifications'
      fullPath: '/api/webhooks/gmail-notifications'
      preLoaderRoute: typeof ApiWebhooksGmailNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/telegram': {
      id: '/api/webhooks/telegram'
      path: '/api/webhooks/telegram'
      fullPath: '/api/webhooks/telegram'
      preLoaderRoute: typeof ApiWebhooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/gmail-notifications': {
      id: '/api/public/webhooks/gmail-notifications'
      path: '/api/public/webhooks/gmail-notifications'
      fullPath: '/api/public/webhooks/gmail-notifications'
      preLoaderRoute: typeof ApiPublicWebhooksGmailNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/telegram': {
      id: '/api/public/webhooks/telegram'
      path: '/api/public/webhooks/telegram'
      fullPath: '/api/public/webhooks/telegram'
      preLoaderRoute: typeof ApiPublicWebhooksTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminAutomationsRoute: typeof AuthenticatedAdminAutomationsRoute
  AuthenticatedAdminDraftsRoute: typeof AuthenticatedAdminDraftsRoute
  AuthenticatedAdminKbRoute: typeof AuthenticatedAdminKbRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminReviewRoute: typeof AuthenticatedAdminReviewRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAutomationsLogsRoute: typeof AuthenticatedAutomationsLogsRoute
  AuthenticatedAutomationsTelegramRoute: typeof AuthenticatedAutomationsTelegramRoute
  AuthenticatedChatbotKbRoute: typeof AuthenticatedChatbotKbRoute
  AuthenticatedChatbotLeadsRoute: typeof AuthenticatedChatbotLeadsRoute
  AuthenticatedChatbotLiveRoute: typeof AuthenticatedChatbotLiveRoute
  AuthenticatedChatbotReviewRoute: typeof AuthenticatedChatbotReviewRoute
  AuthenticatedEmailDraftsHistoryRoute: typeof AuthenticatedEmailDraftsHistoryRoute
  AuthenticatedEmailDraftsKbSyncRoute: typeof AuthenticatedEmailDraftsKbSyncRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAutomationsIndexRoute: typeof AuthenticatedAutomationsIndexRoute
  AuthenticatedChatbotIndexRoute: typeof AuthenticatedChatbotIndexRoute
  AuthenticatedEmailDraftsIndexRoute: typeof AuthenticatedEmailDraftsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminAutomationsRoute: AuthenticatedAdminAutomationsRoute,
  AuthenticatedAdminDraftsRoute: AuthenticatedAdminDraftsRoute,
  AuthenticatedAdminKbRoute: AuthenticatedAdminKbRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminReviewRoute: AuthenticatedAdminReviewRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAutomationsLogsRoute: AuthenticatedAutomationsLogsRoute,
  AuthenticatedAutomationsTelegramRoute: AuthenticatedAutomationsTelegramRoute,
  AuthenticatedChatbotKbRoute: AuthenticatedChatbotKbRoute,
  AuthenticatedChatbotLeadsRoute: AuthenticatedChatbotLeadsRoute,
  AuthenticatedChatbotLiveRoute: AuthenticatedChatbotLiveRoute,
  AuthenticatedChatbotReviewRoute: AuthenticatedChatbotReviewRoute,
  AuthenticatedEmailDraftsHistoryRoute: AuthenticatedEmailDraftsHistoryRoute,
  AuthenticatedEmailDraftsKbSyncRoute: AuthenticatedEmailDraftsKbSyncRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAutomationsIndexRoute: AuthenticatedAutomationsIndexRoute,
  AuthenticatedChatbotIndexRoute: AuthenticatedChatbotIndexRoute,
  AuthenticatedEmailDraftsIndexRoute: AuthenticatedEmailDraftsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
  ApiPublicWorkspaceRoute: ApiPublicWorkspaceRoute,
  ApiWebhooksGmailNotificationsRoute: ApiWebhooksGmailNotificationsRoute,
  ApiWebhooksTelegramRoute: ApiWebhooksTelegramRoute,
  ApiPublicWebhooksGmailNotificationsRoute:
    ApiPublicWebhooksGmailNotificationsRoute,
  ApiPublicWebhooksTelegramRoute: ApiPublicWebhooksTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
